name: Push Image Without Dockerfile

on:
  push:
    branches:
      - main

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull any base image (since no Dockerfile)
      - name: Pull base image
        run: docker pull hello-world

      # Tag the image with your Docker Hub name
      - name: Tag image
        run: docker tag hello-world ${{ secrets.DOCKER_USERNAME }}/workflow:latest

      # Push to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/workflow:latest
