name: Docker CI/CD

on:
  push:
    branches:
      - main   # ya jo branch tum use karte ho

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Code checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker login using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/workflow:latest .

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/workflow:latest
