name: Push Image Without Dockerfile

on:
  push:
    branches:
      - main

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Pull a stable base image (like alpine or hello-world)
      - name: Pull base image
        run: docker pull hello-world

      # 4️⃣ Tag the image properly
      - name: Tag image
        run: |
          docker tag hello-world ${{ secrets.DOCKER_USERNAME }}/workflow:latest

      # 5️⃣ Push to Docker Hub
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/workflow:latest
